### ISSUE TITLE
PSR-4 Autoloading Compliance

### ISSUE THREAD

**Issue by elanclarkson** [ollywarren/laravel-go-cardless#5]
Hi, thank you for this useful package!

Composer gives me the following warning when using it however:

`Class Ollywarren\LaravelGoCardless\src\services\GoCardlessService located in ./vendor/ollywarren/laravel-go-cardless/src/services/GoCardlessService.php does not comply with psr-4 autoloading standard. Skipping.`

... Which could be a problem in some environments as the files will not be autoloaded. Please either change the folder structure or update the namespace to accurately reflect the current structure.

In the meantime I have needed to add `vendor/ollywarren/laravel-go-cardless/src/` to my autoload classmap to ensure 
the files are loaded.

**Comment by ollywarren** [comment]
Hi,

Thanks for the feedback. I ought to really get this updated for up to date standards. I have largely moved out of the PHP space but will take a look at this package and get it updated.

**Comment by ollywarren** [comment]
Fixed and Updated in 1.1.0-dev Closing and will be published with updated package.
